platform :ios, '15.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'ScanditBarcodeCapturePlugin' do
  capacitor_pods
  pod 'ScanditCapacitorDatacaptureCore', :path => '../../scandit-capacitor-datacapture-core/ScanditCapacitorDatacaptureCore.podspec'
end

target 'ScanditBarcodeCapturePluginTests' do
  capacitor_pods
end
